---
- name: include gluster packages
  include: packages.yml
  when: ansible_os_family == 'RedHat'

- name: set_fact gluster_master
  set_fact:
    gluster_master: '{{hostvars[groups[glusterfs_server_group][0]].ansible_hostname}}'
  run_once: True
  tags:
    - setfact
    - create_volumes

- name: include gluster firewalld
  include: firewalld.yml
  when: not disable_firewalld

- name: include glusterfs configure server
  include: configure-server.yml
  when: glusterfs_volumes and glusterfs_install_server

- name: include glusterfs configure client
  include: configure-client.yml
  when: glusterfs_mounts and glusterfs_install_client
